name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo yum update -y
          sudo yum install -y git docker
          sudo systemctl start docker
          sudo systemctl enable docker

          if [ ! -d "HMS-DevSecOps" ]; then
            git clone https://github.com/attiq140/HMS-DevSecOps.git
          fi
          cd HMS-DevSecOps
          git pull origin main

          docker stop hms-container || true
          docker rm hms-container || true
          docker build -t hms-frontend . | tee docker_build.log
          docker run -d -p 5173:80 --name hms-container hms-frontend
        EOF
